MSVC compiler errors + warnings fixed: - warning C4673: throwing 'caf::test::detail::require_error' the following types will not be considered at the catch site - warning C4670: 'logic_error': this base class is inaccessible - error C3083: 'high_resolution_clock': the symbol to the left of a '::' must be a type (compiling source file test/tests.cpp) - warning C4855: implicit capture of 'this' via '[=]' is deprecated in '/std:c++20'